---
author: "Tom Lous"
date: "23 April 2016"
output:
  html_document:
    keep_md: yes
  pdf_document: default
---

# Quiz 3
## Question 1



```{r}
```


### Answer

```{r}
```

---

## Question 1



```{r}
```


### Answer

```{r}
```

---

## Question 1



```{r}
```


### Answer

```{r}
```

---

## Question 1



```{r}
```


### Answer

```{r}
```

---

## Question 1



```{r}
```


### Answer

```{r}
```

---

## Question 1



```{r}
```


### Answer

```{r}
```

---

## Question 1



```{r}
```


### Answer

```{r}
```

---

## Question 1



```{r}
```


### Answer

```{r}
```

---

## Question 1



```{r}
```


### Answer

```{r}
```

---

## Question 1



```{r}
```


### Answer

```{r}
```

---

## Question 1



```{r}
```


### Answer

```{r}
```

---

## Question 1



```{r}
```


### Answer

```{r}
```

---

## Question 1



```{r}
```


### Answer

```{r}
```

---

## Question 1



```{r}
```


### Answer

```{r}
```

---

## Question 1



```{r}
```


### Answer

```{r}
```

---

## Question 1



```{r}
```


### Answer

```{r}
```

---

## Question 1



```{r}
```


### Answer

```{r}
```

---

## Question 1



```{r}
```


### Answer

```{r}
```

---

## Question 1



```{r}
```


### Answer

```{r}
```

---

## Question 1



```{r}
```


### Answer

```{r}
```

---

## Question 1



```{r}
```


### Answer

```{r}
```

---

